version: '3.4'

services:
  
  pgadmin:
  image: dpage/pgadmin4
  environment:
    PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
    PGADMIN_DEFAULT_PASSWORD: password
    PGADMIN_LISTEN_PORT: 80
  ports:
    - 15432:80
  volumes:
    - pgadmin:/var/lib/pgadmin
  depends_on:
    - postgres

  postgres_db:
    image: postgres:15
    container_name: 
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  baseapp:
    container_name: baseapp
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      -80:4200/tcp

