version: '3.4'

services:
  postgres_db:
    image: postgres:15
    container_name: 
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data